# Data validation and pre-processing technique

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import library packages
import pandas as p
import numpy as n

In [3]:
#Load given dataset
data = p.read_csv("demo1.csv")

Before drop the given dataset

In [4]:
data.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47

In [5]:
data.shape

(1078, 13)

After drop the given dataset

In [6]:
df=data.dropna()
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47

In [7]:
df.shape

(1078, 13)

In [8]:
#show columns
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [9]:
df['slug'].unique()

array(['ethereum', 'bitcoin', 'cardano', 'binance-coin'], dtype=object)

In [10]:
df['ranknow'].unique()

array([ 3,  1, 10, 16], dtype=int64)

In [11]:
df["symbol"].unique()

array(['ETH', 'BTC', 'ADA', 'BNB'], dtype=object)

In [12]:
df["open"].unique()

array([ 2.83    ,  2.79    ,  0.706136, ..., 12.61    , 13.03    ,
       12.96    ])

In [13]:
df["high"].unique()

array([3.54000e+00, 2.80000e+00, 8.79810e-01, 7.29854e-01, 1.13000e+00,
       1.29000e+00, 1.97000e+00, 2.26000e+00, 1.88000e+00, 1.70000e+00,
       1.58000e+00, 1.33000e+00, 1.32000e+00, 1.53000e+00, 1.56000e+00,
       1.48000e+00, 1.41000e+00, 1.36000e+00, 1.24000e+00, 1.20000e+00,
       1.19000e+00, 1.21000e+00, 1.37000e+00, 1.40000e+00, 1.39000e+00,
       1.35000e+00, 1.31000e+00, 1.30000e+00, 1.34000e+00, 1.28000e+00,
       1.26000e+00, 1.22000e+00, 1.17000e+00, 1.11000e+00, 1.04000e+00,
       9.49387e-01, 1.05000e+00, 9.52698e-01, 9.09204e-01, 8.88102e-01,
       9.11883e-01, 9.47741e-01, 9.57326e-01, 9.19337e-01, 9.08910e-01,
       9.08571e-01, 8.25665e-01, 7.87544e-01, 7.91277e-01, 7.25677e-01,
       6.75830e-01, 7.46722e-01, 7.34307e-01, 6.91120e-01, 7.09204e-01,
       6.93126e-01, 6.74438e-01, 6.53944e-01, 6.56301e-01, 6.33138e-01,
       6.92296e-01, 6.49022e-01, 6.39506e-01, 6.57789e-01, 6.30240e-01,
       6.12240e-01, 5.72714e-01, 5.68861e-01, 5.63460e-01, 5.52234e-01,
       5.21546e-01, 5.01898e-01, 4.82988e-01, 6.19466e-01, 6.11743e-01,
       5.77396e-01, 6.88192e-01, 7.57517e-01, 8.98172e-01, 1.06000e+00,
       1.08000e+00, 1.10000e+00, 1.07000e+00, 9.91259e-01, 9.89848e-01,
       9.43787e-01, 1.03000e+00, 9.45278e-01, 9.13919e-01, 9.17309e-01,
       9.06113e-01, 9.21516e-01, 9.44732e-01, 1.01000e+00, 9.55735e-01,
       9.78743e-01, 9.84132e-01, 9.69057e-01, 9.48055e-01, 8.99493e-01,
       9.03643e-01, 9.00051e-01, 9.29293e-01, 9.14153e-01, 8.95054e-01,
       8.86736e-01, 8.78017e-01, 8.37664e-01, 8.59575e-01, 8.72821e-01,
       8.82436e-01, 8.50791e-01, 8.23645e-01, 8.24454e-01, 8.61590e-01,
       9.29762e-01, 9.89394e-01, 1.02000e+00, 9.97611e-01, 9.39493e-01,
       9.25874e-01, 9.43185e-01, 9.17390e-01, 9.09526e-01, 8.82940e-01,
       8.82818e-01, 8.82556e-01, 8.97453e-01, 8.61538e-01, 1.35980e+02,
       1.47490e+02, 1.46930e+02, 1.39890e+02, 1.25600e+02, 1.08130e+02,
       1.15000e+02, 1.18800e+02, 1.24660e+02, 1.13440e+02, 1.15780e+02,
       1.13460e+02, 1.22000e+02, 1.18680e+02, 1.17450e+02, 1.18700e+02,
       1.19800e+02, 1.15810e+02, 1.18760e+02, 1.25300e+02, 1.25250e+02,
       1.24500e+02, 1.23620e+02, 1.23000e+02, 1.24000e+02, 1.26930e+02,
       1.33850e+02, 1.33220e+02, 1.36000e+02, 1.35460e+02, 1.30580e+02,
       1.32590e+02, 1.32250e+02, 1.29900e+02, 1.29780e+02, 1.29400e+02,
       1.22500e+02, 1.23840e+02, 1.23470e+02, 1.23100e+02, 1.19000e+02,
       1.11420e+02, 1.08990e+02, 1.10100e+02, 1.09600e+02, 1.11790e+02,
       1.10300e+02, 1.04700e+02, 1.03700e+02, 1.01600e+02, 1.02210e+02,
       1.11110e+02, 1.10220e+02, 1.14300e+02, 1.14990e+02, 1.09960e+02,
       1.08800e+02, 1.08330e+02, 1.06470e+02, 1.05490e+02, 1.04000e+02,
       1.01740e+02, 9.99900e+01, 9.81200e+01, 9.76600e+01, 9.23000e+01,
       9.09800e+01, 8.31100e+01, 8.00000e+01, 7.50000e+01, 7.45600e+01,
       7.83000e+01, 8.70000e+01, 9.02800e+01, 9.82500e+01, 9.87000e+01,
       1.01900e+02, 9.98600e+01, 9.99700e+01, 9.88000e+01, 9.52000e+01,
       9.31000e+01, 9.19500e+01, 9.20000e+01, 9.68200e+01, 9.59900e+01,
       9.73300e+01, 9.74700e+01, 9.70000e+01, 1.00580e+02, 1.02500e+02,
       1.07990e+02, 1.11340e+02, 1.08000e+02, 1.05780e+02, 1.05950e+02,
       1.07770e+02, 1.07380e+02, 1.06750e+02, 1.05750e+02, 1.03900e+02,
       1.05190e+02, 1.09350e+02, 1.13250e+02, 1.12300e+02, 1.13750e+02,
       1.14690e+02, 1.23060e+02, 1.23010e+02, 1.24910e+02, 1.23500e+02,
       1.21390e+02, 1.22990e+02, 1.22750e+02, 1.27240e+02, 1.27320e+02,
       1.23700e+02, 1.35750e+02, 1.40890e+02, 1.45810e+02, 1.46500e+02,
       1.38340e+02, 1.44500e+02, 1.31440e+02, 1.27340e+02, 1.25940e+02,
       1.24720e+02, 1.29060e+02, 1.29740e+02, 1.37830e+02, 1.36080e+02,
       1.37580e+02, 1.35850e+02, 1.32720e+02, 1.32760e+02, 1.33200e+02,
       1.31770e+02, 1.35620e+02, 1.28610e+02, 1.33940e+02, 1.32730e+02,
       1.27460e+02, 1.29690e+02, 1.34930e+02, 1.34740e+02, 1.35630e+02,
       1.40610e+02, 1.38350e+02, 1.34630e+02, 1.33590e+02, 1.23630e+02,
       1.30090e+02, 1.30440e+02, 1.29660e+02, 1.30270e+02, 1.27470e+02,
       1.31750e+02, 1.31500e+02, 1.31810e+02, 1.35660e+02, 1.38660e+02,
       1.44120e+02, 1.45390e+02, 1.52230e+02, 1.47420e+02, 1.55960e+02,
       1.77480e+02, 1.74910e+02, 1.84820e+02, 1.96270e+02, 2.13620e+02,
       2.17420e+02, 1.98870e+02, 1.88410e+02, 1.96440e+02, 1.98620e+02,
       2.04790e+02, 2.09160e+02, 2.05180e+02, 2.06650e+02, 2.07760e+02,
       2.15050e+02, 2.31010e+02, 2.50660e+02, 2.63000e+02, 3.04170e+02,
       3.38660e+02, 3.70820e+02, 3.50700e+02, 3.51270e+02, 3.62810e+02,
       4.14050e+02, 4.25900e+02, 4.37890e+02, 4.50260e+02, 5.00580e+02,
       7.03780e+02, 8.06110e+02, 5.99650e+02, 7.33400e+02, 7.80850e+02,
       8.44970e+02, 8.07360e+02, 8.10680e+02, 9.28540e+02, 1.00196e+03,
       1.07756e+03, 1.14697e+03, 1.15614e+03, 1.13308e+03, 1.05542e+03,
       1.09600e+03, 1.15612e+03, 1.15436e+03, 1.04238e+03, 8.54640e+02,
       8.02510e+02, 9.21930e+02, 9.97230e+02, 1.00158e+03, 9.01940e+02,
       9.41790e+02, 9.04650e+02, 8.86160e+02, 8.82250e+02, 7.54830e+02,
       6.79320e+02, 7.07230e+02, 7.29160e+02, 6.54270e+02, 6.66740e+02,
       6.80910e+02, 6.84390e+02, 6.82700e+02, 7.77750e+02, 7.77510e+02,
       7.47060e+02, 7.48610e+02, 7.66600e+02, 7.60580e+02, 7.75350e+02,
       8.20310e+02, 8.34150e+02, 8.59510e+02, 9.52400e+02, 1.01712e+03,
       9.65740e+02, 8.70680e+02, 8.64360e+02, 8.71190e+02, 9.21480e+02,
       9.28520e+02, 8.61290e+02, 8.55690e+02, 8.72810e+02, 8.66160e+02,
       8.42910e+02, 8.41490e+02, 8.70960e+02, 8.86390e+02, 8.81200e+02,
       8.70150e+02, 8.51570e+02, 8.22430e+02, 8.61450e+02, 8.97020e+02,
       8.93000e+02, 8.32500e+02, 8.36870e+02, 8.30500e+02, 8.31870e+02,
       8.53520e+02, 8.44720e+02, 8.26480e+02, 8.40170e+02, 8.37320e+02,
       8.19810e+02, 7.83200e+02, 7.21820e+02, 7.12270e+02, 7.03710e+02,
       7.12460e+02, 6.72900e+02, 6.57990e+02, 6.91720e+02, 6.61840e+02,
       6.65100e+02, 6.56950e+02, 6.45760e+02, 6.31770e+02, 6.27730e+02,
       5.82960e+02, 6.14480e+02, 6.39910e+02, 6.07610e+02, 5.41380e+02,
       6.03800e+02, 5.94050e+02, 5.84140e+02, 5.73380e+02, 5.70480e+02,
       7.02910e+02, 6.96220e+02, 6.74280e+02, 6.69770e+02, 6.65340e+02,
       6.35140e+02, 6.43950e+02, 6.44760e+02, 6.38420e+02, 6.48030e+02,
       6.44200e+02, 6.39530e+02, 6.39140e+02, 6.37520e+02, 6.32680e+02,
       6.22390e+02, 6.22000e+02, 6.09740e+02, 6.04590e+02, 5.72550e+02,
       5.70240e+02, 5.86560e+02, 5.85440e+02, 5.90030e+02, 5.80560e+02,
       5.26020e+02, 5.04860e+02, 4.92370e+02, 4.83020e+02, 4.95340e+02,
       4.95050e+02, 4.49570e+02, 4.54650e+02, 4.63570e+02, 4.66320e+02,
       4.62560e+02, 4.57420e+02, 4.55730e+02, 4.43370e+02, 4.29770e+02,
       4.39610e+02, 4.27400e+02, 4.69750e+02, 5.19000e+02, 5.42380e+02,
       5.33520e+02, 4.98600e+02, 5.03550e+02, 5.10870e+02, 5.10570e+02,
       5.03220e+02, 4.93250e+02, 5.00460e+02, 5.00300e+02, 4.64540e+02,
       4.59330e+02, 4.47530e+02, 4.51640e+02, 4.51100e+02, 4.60610e+02,
       4.57930e+02, 4.49400e+02, 4.39770e+02, 4.40970e+02, 4.48040e+02,
       4.46130e+02, 4.48400e+02, 4.52690e+02, 4.55770e+02, 4.55340e+02,
       4.42260e+02, 4.41980e+02, 4.46660e+02, 4.49800e+02, 4.50660e+02,
       4.51980e+02, 4.49770e+02, 4.47550e+02, 4.91440e+02, 3.22260e-02,
       3.00880e-02, 2.74250e-02, 2.28060e-02, 2.21540e-02, 2.15420e-02,
       2.10500e-02, 2.35980e-02, 2.28070e-02, 2.24460e-02, 2.25760e-02,
       2.67630e-02, 3.38160e-02, 3.82680e-02, 3.36410e-02, 3.07490e-02,
       2.96280e-02, 2.73600e-02, 2.71120e-02, 3.08550e-02, 3.08060e-02,
       2.87440e-02, 2.80510e-02, 2.89560e-02, 2.78460e-02, 2.75600e-02,
       2.74630e-02, 2.68530e-02, 2.98370e-02, 2.88740e-02, 3.07150e-02,
       2.92190e-02, 2.49770e-02, 2.32130e-02, 2.38490e-02, 2.30060e-02,
       2.36090e-02, 2.33470e-02, 2.63930e-02, 3.50600e-02, 3.33480e-02,
       2.96590e-02, 2.79520e-02, 2.63000e-02, 2.67880e-02, 2.77730e-02,
       2.81700e-02, 2.74360e-02, 2.71220e-02, 2.84780e-02, 3.23000e-02,
       2.97090e-02, 2.90340e-02, 2.86780e-02, 2.85970e-02, 3.04470e-02,
       3.98550e-02, 5.71270e-02, 1.31730e-01, 1.46906e-01, 1.28303e-01,
       1.31352e-01, 1.38869e-01, 1.39220e-01, 1.45946e-01, 1.36404e-01,
       1.32855e-01, 1.24176e-01, 1.20726e-01, 1.38660e-01, 1.19794e-01,
       1.21383e-01, 1.38008e-01, 1.41854e-01, 2.40753e-01, 2.33209e-01,
       4.47192e-01, 5.92417e-01, 5.26496e-01, 5.89589e-01, 5.33705e-01,
       5.23619e-01, 4.78974e-01, 4.50368e-01, 4.16661e-01, 4.39700e-01,
       4.30086e-01, 4.30827e-01, 4.18934e-01, 5.56879e-01, 7.77385e-01,
       7.54446e-01, 7.30051e-01, 7.94646e-01, 1.09000e+00, 1.25000e+00,
       9.99329e-01, 9.19436e-01, 8.16252e-01, 7.91522e-01, 9.32269e-01,
       9.69325e-01, 8.81961e-01, 8.84506e-01, 7.80621e-01, 6.78517e-01,
       7.11008e-01, 6.88520e-01, 7.26242e-01, 7.06391e-01, 6.31485e-01,
       5.92231e-01, 6.36009e-01, 6.83023e-01, 6.52848e-01, 6.32956e-01,
       6.81946e-01, 6.69373e-01, 6.24799e-01, 5.50252e-01, 5.35322e-01,
       4.19460e-01, 5.01639e-01, 4.80140e-01, 3.99523e-01, 3.78719e-01,
       3.77219e-01, 3.67504e-01, 3.94133e-01, 4.62766e-01, 4.05196e-01,
       3.93307e-01, 3.87018e-01, 4.01321e-01, 4.16687e-01, 4.12404e-01,
       4.28074e-01, 4.20010e-01, 3.96608e-01, 4.04329e-01, 3.83513e-01,
       3.72116e-01, 3.51240e-01, 3.52488e-01, 3.54572e-01, 3.46955e-01,
       3.41189e-01, 3.36163e-01, 3.11973e-01, 3.07058e-01, 3.09129e-01,
       3.03588e-01, 3.17723e-01, 3.03019e-01, 2.87598e-01, 2.54354e-01,
       2.25115e-01, 2.26558e-01, 2.27322e-01, 2.37342e-01, 2.29146e-01,
       2.33147e-01, 2.01611e-01, 1.86788e-01, 1.79160e-01, 1.61959e-01,
       1.97648e-01, 2.12004e-01, 2.27502e-01, 2.21969e-01, 2.02812e-01,
       2.01190e-01, 1.89128e-01, 1.85421e-01, 1.69225e-01, 1.65599e-01,
       1.60614e-01, 1.51782e-01, 1.60559e-01, 1.60825e-01, 1.58797e-01,
       1.73438e-01, 1.79172e-01, 1.56204e-01, 1.50481e-01, 1.51469e-01,
       1.58452e-01, 1.65656e-01, 1.57820e-01, 1.66431e-01, 2.14525e-01,
       2.18382e-01, 2.06495e-01, 2.23444e-01, 2.56646e-01, 2.72641e-01,
       2.62368e-01, 2.73836e-01, 3.01641e-01, 3.07552e-01, 2.96879e-01,
       2.89623e-01, 3.18699e-01, 3.12805e-01, 2.94972e-01, 3.07469e-01,
       3.64954e-01, 3.87901e-01, 3.64297e-01, 3.63261e-01, 3.76704e-01,
       3.89749e-01, 3.70777e-01, 3.73605e-01, 3.65933e-01, 3.49948e-01,
       3.48219e-01, 3.28426e-01, 3.27908e-01, 2.99462e-01, 2.83410e-01,
       2.90151e-01, 2.86088e-01, 2.78760e-01, 2.60186e-01, 2.63111e-01,
       2.46809e-01, 2.48354e-01, 2.60785e-01, 2.61169e-01, 2.50076e-01,
       2.26150e-01, 2.13302e-01, 2.10636e-01, 2.05492e-01, 1.96436e-01,
       1.94977e-01, 2.08739e-01, 1.15841e-01, 1.09013e-01, 1.08479e-01,
       1.09019e-01, 1.11264e-01, 1.08138e-01, 1.08349e-01, 1.06266e-01,
       1.01211e-01, 1.06978e-01, 1.07756e-01, 1.44653e-01, 1.32988e-01,
       1.49765e-01, 2.26925e-01, 2.60625e-01, 3.49976e-01, 4.09654e-01,
       4.75992e-01, 1.46000e+00, 1.38000e+00, 1.45000e+00, 2.11000e+00,
       2.75000e+00, 2.33000e+00, 2.69000e+00, 2.91000e+00, 2.72000e+00,
       2.96000e+00, 2.66000e+00, 2.73000e+00, 2.54000e+00, 2.31000e+00,
       2.17000e+00, 2.37000e+00, 2.41000e+00, 2.39000e+00, 2.85000e+00,
       2.02000e+00, 1.12000e+00, 1.51000e+00, 1.00000e+00, 9.50177e-01,
       8.49217e-01, 9.27197e-01, 8.14797e-01, 9.37029e-01, 9.09132e-01,
       8.16384e-01, 7.81775e-01, 7.40154e-01, 7.77400e-01, 7.88347e-01,
       9.36568e-01, 9.40082e-01, 1.43000e+00, 1.98000e+00, 2.03000e+00,
       1.86000e+00, 1.74000e+00, 1.71000e+00, 1.61000e+00, 1.60000e+00,
       1.47000e+00, 1.44000e+00, 1.54000e+00, 1.68000e+00, 1.42000e+00,
       1.27000e+00, 1.64000e+00, 1.67000e+00, 1.82000e+00, 2.06000e+00,
       2.07000e+00, 1.92000e+00, 1.62000e+00, 1.66000e+00, 1.96000e+00,
       1.94000e+00, 1.95000e+00, 2.05000e+00, 2.14000e+00, 2.12000e+00,
       2.38000e+00, 2.58000e+00, 2.78000e+00, 2.87000e+00, 2.70000e+00,
       2.82000e+00, 2.88000e+00, 3.16000e+00, 4.41000e+00, 4.73000e+00,
       6.75000e+00, 6.22000e+00, 6.55000e+00, 5.79000e+00, 5.70000e+00,
       5.21000e+00, 5.13000e+00, 5.29000e+00, 6.96000e+00, 1.06200e+01,
       1.13000e+01, 1.02000e+01, 9.53000e+00, 8.76000e+00, 8.84000e+00,
       8.70000e+00, 9.12000e+00, 9.58000e+00, 9.54000e+00, 1.67200e+01,
       2.35100e+01, 2.27700e+01, 1.92200e+01, 2.03200e+01, 1.77100e+01,
       2.31500e+01, 2.49100e+01, 2.36700e+01, 2.22500e+01, 2.36000e+01,
       1.96300e+01, 1.55400e+01, 1.59600e+01, 1.56400e+01, 1.66500e+01,
       1.62500e+01, 1.44500e+01, 1.39600e+01, 1.41900e+01, 1.41400e+01,
       1.35900e+01, 1.34400e+01, 1.38100e+01, 1.36700e+01, 1.27700e+01,
       1.14100e+01, 1.13900e+01, 1.04600e+01, 1.02700e+01, 9.75000e+00,
       8.55000e+00, 8.56000e+00, 9.22000e+00, 8.72000e+00, 9.89000e+00,
       1.03600e+01, 9.35000e+00, 9.40000e+00, 1.06500e+01, 1.12800e+01,
       1.12000e+01, 1.18700e+01, 1.17000e+01, 1.11900e+01, 1.01900e+01,
       9.81000e+00, 9.73000e+00, 9.84000e+00, 9.49000e+00, 1.00600e+01,
       1.11000e+01, 1.11800e+01, 1.06700e+01, 1.05400e+01, 1.04500e+01,
       1.03900e+01, 1.04400e+01, 1.01500e+01, 1.01300e+01, 9.14000e+00,
       8.33000e+00, 8.35000e+00, 8.42000e+00, 1.10000e+01, 9.39000e+00,
       9.50000e+00, 8.96000e+00, 9.26000e+00, 9.24000e+00, 1.02900e+01,
       1.09100e+01, 1.19800e+01, 1.48400e+01, 1.42300e+01, 1.29100e+01,
       1.22300e+01, 1.22500e+01, 1.17300e+01, 1.07500e+01, 1.26500e+01,
       1.39500e+01, 1.26200e+01, 1.26400e+01, 1.26300e+01, 1.25100e+01,
       1.25500e+01, 1.24000e+01, 1.29500e+01, 1.37600e+01, 1.38400e+01,
       1.35800e+01, 1.30600e+01, 1.24600e+01, 1.23900e+01, 1.24300e+01,
       1.27200e+01, 1.33500e+01, 1.38300e+01, 1.56200e+01, 1.59300e+01,
       1.47100e+01, 1.47700e+01, 1.53300e+01, 1.54000e+01, 1.51600e+01,
       1.43100e+01, 1.44100e+01, 1.47800e+01, 1.46800e+01, 1.45000e+01,
       1.48000e+01, 1.39700e+01, 1.39200e+01, 1.48100e+01, 1.50500e+01,
       1.40900e+01, 1.31500e+01, 1.35500e+01, 1.31700e+01, 1.32700e+01,
       1.25700e+01, 1.29700e+01, 1.62200e+01, 1.43700e+01, 1.47900e+01,
       1.39300e+01, 1.31900e+01, 1.33700e+01, 1.32000e+01])

In [14]:
df["low"].unique()

array([ 2.52    ,  0.714725,  0.629191, ..., 12.2     , 12.64    ,
       12.7     ])

In [15]:
df["close"].unique()

array([2.77000e+00, 7.53325e-01, 7.01897e-01, 7.08448e-01, 1.07000e+00,
       1.22000e+00, 1.83000e+00, 1.69000e+00, 1.57000e+00, 1.20000e+00,
       1.09000e+00, 1.26000e+00, 1.46000e+00, 1.40000e+00, 1.38000e+00,
       1.35000e+00, 1.23000e+00, 1.14000e+00, 1.16000e+00, 1.15000e+00,
       1.19000e+00, 1.18000e+00, 1.32000e+00, 1.36000e+00, 1.29000e+00,
       1.27000e+00, 1.34000e+00, 1.30000e+00, 1.25000e+00, 1.24000e+00,
       1.21000e+00, 1.17000e+00, 9.82978e-01, 1.04000e+00, 9.36003e-01,
       8.75622e-01, 9.44410e-01, 9.07175e-01, 8.74231e-01, 8.53685e-01,
       8.82391e-01, 9.38445e-01, 9.19047e-01, 9.01796e-01, 8.93406e-01,
       8.13610e-01, 7.36223e-01, 7.85964e-01, 7.20839e-01, 5.82886e-01,
       6.61146e-01, 7.38644e-01, 6.90215e-01, 6.78574e-01, 6.87171e-01,
       6.68379e-01, 6.28643e-01, 6.50645e-01, 6.09388e-01, 6.21716e-01,
       6.50628e-01, 6.27857e-01, 6.34963e-01, 6.26030e-01, 6.07655e-01,
       5.22968e-01, 5.61878e-01, 5.36495e-01, 5.47178e-01, 5.17734e-01,
       4.89014e-01, 4.34829e-01, 4.47329e-01, 5.67702e-01, 5.39657e-01,
       5.63590e-01, 6.16039e-01, 7.31317e-01, 8.69641e-01, 1.00000e+00,
       9.16627e-01, 1.06000e+00, 9.89789e-01, 1.01000e+00, 8.99050e-01,
       8.95637e-01, 9.26032e-01, 9.27974e-01, 1.03000e+00, 9.99278e-01,
       9.34348e-01, 7.91829e-01, 8.95711e-01, 9.04096e-01, 8.88812e-01,
       9.06368e-01, 9.28962e-01, 9.93319e-01, 9.55532e-01, 9.24920e-01,
       9.76140e-01, 9.68018e-01, 9.46969e-01, 9.00191e-01, 8.63537e-01,
       8.84183e-01, 8.67951e-01, 9.15703e-01, 8.78614e-01, 8.73119e-01,
       8.74800e-01, 8.21210e-01, 8.12143e-01, 8.40041e-01, 8.62438e-01,
       8.35500e-01, 8.11264e-01, 8.22118e-01, 7.92167e-01, 8.40396e-01,
       9.29762e-01, 9.76973e-01, 9.52884e-01, 9.93022e-01, 9.91182e-01,
       9.40701e-01, 9.20127e-01, 9.08072e-01, 9.03885e-01, 9.00771e-01,
       8.64202e-01, 8.58077e-01, 8.63262e-01, 8.70363e-01, 8.54603e-01,
       8.56365e-01, 1.34210e+02, 1.44540e+02, 1.39000e+02, 1.16990e+02,
       1.05210e+02, 9.77500e+01, 1.12500e+02, 1.15910e+02, 1.12300e+02,
       1.11500e+02, 1.13570e+02, 1.12670e+02, 1.17200e+02, 1.15240e+02,
       1.15000e+02, 1.17980e+02, 1.14220e+02, 1.18760e+02, 1.23010e+02,
       1.23500e+02, 1.21990e+02, 1.22000e+02, 1.22880e+02, 1.23890e+02,
       1.26700e+02, 1.33200e+02, 1.31980e+02, 1.33480e+02, 1.29740e+02,
       1.29000e+02, 1.32300e+02, 1.28800e+02, 1.29300e+02, 1.22290e+02,
       1.22220e+02, 1.21420e+02, 1.21650e+02, 1.18000e+02, 1.08300e+02,
       1.00000e+02, 1.06350e+02, 1.08900e+02, 1.08150e+02, 1.04000e+02,
       9.99800e+01, 9.99900e+01, 9.95100e+01, 1.01700e+02, 1.07400e+02,
       1.08250e+02, 1.10150e+02, 1.09500e+02, 1.07600e+02, 1.02740e+02,
       1.03950e+02, 1.01440e+02, 9.46500e+01, 9.49900e+01, 9.66100e+01,
       8.80500e+01, 9.01300e+01, 7.75300e+01, 8.05300e+01, 6.84300e+01,
       7.02800e+01, 7.45600e+01, 7.65200e+01, 7.66900e+01, 8.67600e+01,
       8.89800e+01, 9.35900e+01, 9.81300e+01, 9.46900e+01, 9.84000e+01,
       9.74500e+01, 9.85000e+01, 9.05800e+01, 9.21700e+01, 8.93900e+01,
       9.07600e+01, 9.16100e+01, 9.55600e+01, 9.45100e+01, 9.69000e+01,
       9.60200e+01, 9.41200e+01, 9.97600e+01, 1.01200e+02, 1.07990e+02,
       1.06090e+02, 1.04500e+02, 1.05140e+02, 1.06220e+02, 1.06750e+02,
       1.03000e+02, 1.02800e+02, 1.05000e+02, 1.06640e+02, 1.09000e+02,
       1.12560e+02, 1.09990e+02, 1.08990e+02, 1.13500e+02, 1.19000e+02,
       1.21210e+02, 1.23300e+02, 1.21150e+02, 1.18500e+02, 1.20040e+02,
       1.22110e+02, 1.20060e+02, 1.26500e+02, 1.22620e+02, 1.22390e+02,
       1.33490e+02, 1.35350e+02, 1.38340e+02, 1.35850e+02, 1.36770e+02,
       1.26740e+02, 1.26430e+02, 1.19150e+02, 1.24150e+02, 1.21660e+02,
       1.27110e+02, 1.25910e+02, 1.35250e+02, 1.33130e+02, 1.34980e+02,
       1.29220e+02, 1.30370e+02, 1.31720e+02, 1.31660e+02, 1.31470e+02,
       1.29650e+02, 1.27040e+02, 1.27430e+02, 1.29120e+02, 1.25950e+02,
       1.27250e+02, 1.28220e+02, 1.28380e+02, 1.33780e+02, 1.34780e+02,
       1.37340e+02, 1.33000e+02, 1.32180e+02, 1.14130e+02, 1.23630e+02,
       1.29010e+02, 1.28550e+02, 1.26940e+02, 1.26000e+02, 1.30690e+02,
       1.30590e+02, 1.30900e+02, 1.35190e+02, 1.38130e+02, 1.40520e+02,
       1.45240e+02, 1.42550e+02, 1.46250e+02, 1.55960e+02, 1.72420e+02,
       1.74610e+02, 1.82210e+02, 1.93760e+02, 2.13620e+02, 1.98230e+02,
       1.86690e+02, 1.77320e+02, 1.96440e+02, 1.98550e+02, 2.04390e+02,
       1.99970e+02, 2.04000e+02, 2.06180e+02, 2.06220e+02, 2.15050e+02,
       2.29100e+02, 2.45240e+02, 2.62500e+02, 2.96410e+02, 3.38110e+02,
       3.39110e+02, 3.26620e+02, 3.42440e+02, 3.60330e+02, 4.07370e+02,
       4.20200e+02, 4.17950e+02, 4.40220e+02, 4.92110e+02, 7.03560e+02,
       5.84610e+02, 5.90830e+02, 7.22430e+02, 7.71440e+02, 7.97820e+02,
       7.74250e+02, 7.99110e+02, 9.28100e+02, 1.00196e+03, 1.03195e+03,
       1.13197e+03, 1.12943e+03, 9.55850e+02, 1.04333e+03, 1.07828e+03,
       1.15117e+03, 1.04511e+03, 8.29450e+02, 6.98230e+02, 7.95870e+02,
       8.93190e+02, 9.88510e+02, 8.78480e+02, 8.73260e+02, 8.92580e+02,
       8.72600e+02, 8.76120e+02, 7.05970e+02, 6.82120e+02, 5.22700e+02,
       6.91960e+02, 6.25320e+02, 6.05660e+02, 6.17180e+02, 6.73410e+02,
       6.65580e+02, 6.82210e+02, 7.61980e+02, 7.35070e+02, 7.27830e+02,
       7.45050e+02, 7.56130e+02, 7.54010e+02, 7.71400e+02, 8.02390e+02,
       8.18720e+02, 8.59510e+02, 9.33530e+02, 9.53290e+02, 8.02000e+02,
       8.42720e+02, 8.46860e+02, 8.68480e+02, 9.13950e+02, 8.63220e+02,
       8.41200e+02, 8.33270e+02, 8.60900e+02, 8.35630e+02, 8.14640e+02,
       8.40000e+02, 8.70960e+02, 8.70200e+02, 8.63910e+02, 8.45590e+02,
       8.22040e+02, 7.97070e+02, 8.53610e+02, 8.85280e+02, 7.71390e+02,
       8.12510e+02, 8.26000e+02, 8.19030e+02, 8.29920e+02, 8.32580e+02,
       8.25370e+02, 8.23830e+02, 8.27960e+02, 8.11910e+02, 7.81550e+02,
       7.12400e+02, 6.73920e+02, 6.82900e+02, 6.81030e+02, 6.72170e+02,
       6.51720e+02, 6.05240e+02, 6.61990e+02, 6.50920e+02, 6.16630e+02,
       6.26270e+02, 6.26600e+02, 6.23030e+02, 5.56140e+02, 5.74160e+02,
       6.05420e+02, 6.05820e+02, 5.46320e+02, 5.38710e+02, 5.82690e+02,
       5.78770e+02, 5.49260e+02, 5.65610e+02, 5.59790e+02, 6.67760e+02,
       6.66780e+02, 6.65510e+02, 6.63860e+02, 6.29150e+02, 6.17450e+02,
       6.36960e+02, 6.27790e+02, 6.34110e+02, 6.32100e+02, 6.38140e+02,
       6.28800e+02, 6.36120e+02, 6.31110e+02, 6.22370e+02, 6.14830e+02,
       6.09890e+02, 5.88770e+02, 5.71490e+02, 5.65040e+02, 5.61270e+02,
       5.83410e+02, 5.83920e+02, 5.80830e+02, 4.71240e+02, 4.95670e+02,
       4.91170e+02, 4.60270e+02, 4.57000e+02, 4.78380e+02, 4.37140e+02,
       4.44720e+02, 4.47530e+02, 4.61910e+02, 4.60500e+02, 4.49420e+02,
       4.53090e+02, 4.42730e+02, 3.65180e+02, 4.20950e+02, 4.21120e+02,
       4.14060e+02, 4.58790e+02, 5.15590e+02, 5.27400e+02, 4.95960e+02,
       4.79640e+02, 5.01570e+02, 4.98170e+02, 4.95770e+02, 4.87920e+02,
       4.91300e+02, 5.00460e+02, 4.61450e+02, 4.58600e+02, 4.36390e+02,
       4.40290e+02, 4.47210e+02, 4.47640e+02, 4.57760e+02, 4.49380e+02,
       4.37760e+02, 4.36400e+02, 4.33480e+02, 4.28960e+02, 4.38820e+02,
       4.40170e+02, 4.49460e+02, 4.54430e+02, 4.38890e+02, 4.41460e+02,
       4.40670e+02, 4.43970e+02, 4.47250e+02, 4.48060e+02, 4.48900e+02,
       4.46260e+02, 4.46180e+02, 4.85720e+02, 2.49690e-02, 2.59320e-02,
       2.08160e-02, 2.19310e-02, 2.14890e-02, 1.85390e-02, 2.09410e-02,
       2.04770e-02, 2.21140e-02, 2.15310e-02, 2.25200e-02, 2.62520e-02,
       3.36410e-02, 3.24650e-02, 3.00490e-02, 2.89480e-02, 2.72170e-02,
       2.66910e-02, 2.70320e-02, 3.06300e-02, 2.84360e-02, 2.77290e-02,
       2.54540e-02, 2.71930e-02, 2.75270e-02, 2.71320e-02, 2.63820e-02,
       2.58660e-02, 2.86070e-02, 2.85830e-02, 3.04370e-02, 2.29860e-02,
       2.13060e-02, 2.26280e-02, 2.20220e-02, 2.06350e-02, 2.18810e-02,
       2.21950e-02, 2.51860e-02, 3.20530e-02, 2.71190e-02, 2.74370e-02,
       2.39770e-02, 2.58080e-02, 2.62300e-02, 2.64450e-02, 2.75800e-02,
       2.57730e-02, 2.63690e-02, 2.80840e-02, 2.95810e-02, 2.83300e-02,
       2.85490e-02, 2.74440e-02, 2.83820e-02, 3.04470e-02, 3.63320e-02,
       5.05930e-02, 1.19744e-01, 8.97180e-02, 1.19883e-01, 1.31352e-01,
       1.32351e-01, 1.31807e-01, 1.35870e-01, 1.27488e-01, 1.17839e-01,
       1.05501e-01, 1.15465e-01, 1.19609e-01, 1.10281e-01, 1.21383e-01,
       1.33891e-01, 1.34281e-01, 2.40753e-01, 2.13467e-01, 4.04665e-01,
       5.13011e-01, 5.18198e-01, 5.31273e-01, 4.86151e-01, 4.77851e-01,
       4.07150e-01, 4.14027e-01, 3.90029e-01, 4.16363e-01, 4.28465e-01,
       4.14176e-01, 4.07701e-01, 5.29299e-01, 6.39243e-01, 7.19695e-01,
       7.28657e-01, 7.82587e-01, 1.08000e+00, 1.11000e+00, 9.99559e-01,
       8.99002e-01, 8.14743e-01, 7.93121e-01, 6.88412e-01, 8.97508e-01,
       8.84124e-01, 8.02262e-01, 7.78587e-01, 6.26493e-01, 6.29102e-01,
       6.59843e-01, 6.50498e-01, 7.07510e-01, 6.13163e-01, 5.70458e-01,
       5.63070e-01, 6.22208e-01, 6.37495e-01, 6.23382e-01, 6.16833e-01,
       6.70286e-01, 6.23204e-01, 5.31913e-01, 5.19315e-01, 4.21672e-01,
       3.90534e-01, 4.38836e-01, 3.79303e-01, 3.27371e-01, 3.69753e-01,
       3.40447e-01, 3.56584e-01, 3.91602e-01, 4.05872e-01, 3.69769e-01,
       3.84315e-01, 3.73314e-01, 3.96908e-01, 4.09368e-01, 4.03810e-01,
       4.19883e-01, 3.85618e-01, 3.91472e-01, 3.78779e-01, 3.64441e-01,
       3.37871e-01, 3.45258e-01, 3.22966e-01, 3.44033e-01, 3.38335e-01,
       3.35536e-01, 3.12581e-01, 3.04397e-01, 2.93504e-01, 2.97106e-01,
       3.00787e-01, 2.97622e-01, 2.85357e-01, 2.47281e-01, 2.21743e-01,
       2.22207e-01, 2.09873e-01, 2.23498e-01, 2.23722e-01, 2.23026e-01,
       1.99562e-01, 1.85709e-01, 1.78878e-01, 1.54763e-01, 1.56155e-01,
       1.97648e-01, 2.04947e-01, 2.13189e-01, 2.03481e-01, 1.89259e-01,
       1.89201e-01, 1.84605e-01, 1.67806e-01, 1.54926e-01, 1.60058e-01,
       1.46882e-01, 1.47209e-01, 1.55919e-01, 1.50768e-01, 1.56385e-01,
       1.72447e-01, 1.55356e-01, 1.48758e-01, 1.44451e-01, 1.48794e-01,
       1.56599e-01, 1.53106e-01, 1.56347e-01, 1.66029e-01, 2.12233e-01,
       2.00532e-01, 2.00853e-01, 2.21390e-01, 2.56646e-01, 2.43724e-01,
       2.60341e-01, 2.72358e-01, 3.01247e-01, 2.90580e-01, 2.85535e-01,
       2.88473e-01, 3.12875e-01, 2.71654e-01, 2.94295e-01, 2.88489e-01,
       3.57874e-01, 3.65057e-01, 3.43318e-01, 3.58693e-01, 3.72420e-01,
       3.69709e-01, 3.60182e-01, 3.66338e-01, 3.50021e-01, 3.35176e-01,
       3.28352e-01, 3.23593e-01, 2.97089e-01, 2.60127e-01, 2.70932e-01,
       2.85890e-01, 2.73434e-01, 2.60155e-01, 2.56375e-01, 2.43664e-01,
       2.45544e-01, 2.43271e-01, 2.56136e-01, 2.48840e-01, 2.24408e-01,
       2.02873e-01, 2.08989e-01, 2.00655e-01, 1.96567e-01, 1.93557e-01,
       1.74783e-01, 2.03190e-01, 1.05870e-01, 1.05138e-01, 1.07737e-01,
       1.04067e-01, 1.07811e-01, 1.06414e-01, 1.04250e-01, 9.98670e-02,
       1.00452e-01, 1.06642e-01, 1.07494e-01, 1.28871e-01, 1.30999e-01,
       1.48848e-01, 2.24421e-01, 2.42912e-01, 3.49079e-01, 3.92572e-01,
       4.46365e-01, 8.76828e-01, 1.44000e+00, 1.97000e+00, 2.38000e+00,
       2.09000e+00, 2.50000e+00, 2.70000e+00, 2.49000e+00, 2.58000e+00,
       2.17000e+00, 2.01000e+00, 2.04000e+00, 2.33000e+00, 2.35000e+00,
       2.20000e+00, 1.99000e+00, 1.58000e+00, 1.05000e+00, 9.73716e-01,
       1.37000e+00, 9.89301e-01, 9.42159e-01, 9.37204e-01, 6.78784e-01,
       7.99709e-01, 8.04198e-01, 7.89589e-01, 9.09202e-01, 8.02425e-01,
       7.47890e-01, 7.02140e-01, 7.15893e-01, 7.70965e-01, 7.83268e-01,
       9.17059e-01, 8.60747e-01, 1.28000e+00, 1.53000e+00, 1.96000e+00,
       1.82000e+00, 1.60000e+00, 1.68000e+00, 1.39000e+00, 1.43000e+00,
       1.54000e+00, 1.56000e+00, 1.33000e+00, 1.31000e+00, 1.64000e+00,
       1.52000e+00, 1.81000e+00, 2.03000e+00, 1.80000e+00, 1.67000e+00,
       1.59000e+00, 1.51000e+00, 1.61000e+00, 1.62000e+00, 1.55000e+00,
       1.72000e+00, 1.87000e+00, 1.85000e+00, 1.94000e+00, 1.92000e+00,
       1.75000e+00, 2.00000e+00, 2.07000e+00, 2.08000e+00, 2.23000e+00,
       2.60000e+00, 2.59000e+00, 2.78000e+00, 2.83000e+00, 2.61000e+00,
       2.48000e+00, 2.71000e+00, 2.68000e+00, 3.16000e+00, 4.00000e+00,
       4.66000e+00, 5.76000e+00, 5.62000e+00, 5.79000e+00, 5.18000e+00,
       4.34000e+00, 4.84000e+00, 5.29000e+00, 6.56000e+00, 9.03000e+00,
       1.01100e+01, 9.32000e+00, 8.81000e+00, 7.84000e+00, 8.64000e+00,
       8.41000e+00, 8.84000e+00, 9.54000e+00, 9.21000e+00, 1.49200e+01,
       2.27600e+01, 1.86600e+01, 1.82600e+01, 1.74100e+01, 1.73900e+01,
       2.10400e+01, 2.23200e+01, 2.21700e+01, 2.07800e+01, 1.95600e+01,
       1.38900e+01, 1.42000e+01, 1.42800e+01, 1.49400e+01, 1.61900e+01,
       1.40700e+01, 1.30100e+01, 1.30900e+01, 1.36300e+01, 1.32300e+01,
       1.32200e+01, 1.32500e+01, 1.35400e+01, 1.27600e+01, 1.12500e+01,
       1.11500e+01, 9.52000e+00, 9.65000e+00, 9.75000e+00, 8.46000e+00,
       6.71000e+00, 8.29000e+00, 8.10000e+00, 8.60000e+00, 9.73000e+00,
       9.26000e+00, 8.70000e+00, 8.99000e+00, 1.04000e+01, 1.09300e+01,
       1.12000e+01, 1.16900e+01, 1.07000e+01, 1.10800e+01, 9.90000e+00,
       9.38000e+00, 8.90000e+00, 9.69000e+00, 9.14000e+00, 9.35000e+00,
       1.06600e+01, 1.04400e+01, 1.05100e+01, 1.02200e+01, 1.03500e+01,
       8.31000e+00, 7.67000e+00, 8.27000e+00, 8.04000e+00, 1.01200e+01,
       8.96000e+00, 9.10000e+00, 9.11000e+00, 8.95000e+00, 9.16000e+00,
       9.98000e+00, 1.00700e+01, 1.17400e+01, 1.27800e+01, 1.20600e+01,
       1.15100e+01, 1.16400e+01, 1.02000e+01, 1.10600e+01, 1.10700e+01,
       1.26200e+01, 1.33600e+01, 1.21900e+01, 1.24500e+01, 1.22600e+01,
       1.24600e+01, 1.21200e+01, 1.18700e+01, 1.20400e+01, 1.22300e+01,
       1.29500e+01, 1.32400e+01, 1.30600e+01, 1.22100e+01, 1.17700e+01,
       1.22800e+01, 1.23500e+01, 1.25800e+01, 1.33800e+01, 1.28800e+01,
       1.52700e+01, 1.32900e+01, 1.46500e+01, 1.43300e+01, 1.52000e+01,
       1.50600e+01, 1.43100e+01, 1.41600e+01, 1.44100e+01, 1.43700e+01,
       1.39400e+01, 1.37000e+01, 1.35300e+01, 1.46600e+01, 1.38200e+01,
       1.29900e+01, 1.29400e+01, 1.31200e+01, 1.28700e+01, 1.25700e+01,
       1.24700e+01, 1.51400e+01, 1.42500e+01, 1.41200e+01, 1.47200e+01,
       1.39300e+01, 1.26300e+01, 1.30000e+01])

In [16]:
#To describe the dataframe
df.describe()

,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
count,1078.000000,1078.000000,1078.000000,1078.000000,1078.000000,1.078000e+03,1.078000e+03,1078.000000,1078.000000
mean,7.535250,140.671620,146.382083,134.116136,140.970731,7.080249e+07,3.511893e+09,0.524541,12.265872
std,6.311488,254.150371,264.755221,241.193733,254.292369,1.620918e+08,4.526472e+09,0.293256,32.991154
min,1.000000,0.018414,0.021050,0.017354,0.018539,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,1.000000,0.683412,0.731115,0.626820,0.687481,2.889678e+05,2.384042e+08,0.276625,0.060000
50%,10.000000,6.685000,8.340000,5.860000,7.190000,9.861245e+06,1.379701e+09,0.537800,0.595000
75%,16.000000,126.237500,129.315000,122.540000,126.322500,7.530740e+07,5.807221e+09,0.785400,6.797500
max,16.000000,1152.730000,1156.140000,1106.610000,1151.170000,1.713770e+09,2.888587e+10,1.000000,349.720000

In [17]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1078 entries, 0 to 1077
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   slug          1078 non-null   object
 1   symbol        1078 non-null   object
 2   name          1078 non-null   object
 3   date          1078 non-null   object
 4   ranknow       1078 non-null   int64
 5   open          1078 non-null   float64
 6   high          1078 non-null   float64
 7   low           1078 non-null   float64
 8   close         1078 non-null   float64
 9   volume        1078 non-null   int64
 10  market_price  1078 non-null   int64
 11  close_ratio   1078 non-null   float64
 12  spread        1078 non-null   float64
dtypes: float64(6), int64(3), object(4)
memory usage: 117.9+ KB

Checking duplicate values of dataframe

In [18]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1073    False
1074    False
1075    False
1076    False
1077    False
Length: 1078, dtype: bool

In [19]:
#find sum of duplicate data
sum(df.duplicated())

0

In [20]:
#Checking sum of missing values
df.isnull().sum()

slug            0
symbol          0
name            0
date            0
ranknow         0
open            0
high            0
low             0
close           0
volume          0
market_price    0
close_ratio     0
spread          0
dtype: int64

In [21]:
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [22]:
df['market_price'].value_counts()

1229098150     2
1726060542     1
955711842      1
959654580      1
10315662000    1
              ..
3147105603     1
5822776642     1
1588081985     1
965354816      1
1374013440     1
Name: market_price, Length: 1077, dtype: int64

In [23]:
print("Minimum market_price value is:", df.market_price.min())
print("Maximum market_price value is:", df.market_price.max())

Minimum market_price value is: 0
Maximum market_price value is: 28885867828

In [24]:
p.Categorical(df['slug']).describe()

              counts     freqs
categories
binance-coin     306  0.283859
bitcoin          388  0.359926
cardano          241  0.223562
ethereum         143  0.132653

In [25]:
p.Categorical(df['market_price']).describe()

             counts     freqs
categories
0                 1  0.000928
9986680           1  0.000928
10045200          1  0.000928
10406700          1  0.000928
10425000          1  0.000928
...             ...       ...
25915636700       1  0.000928
26147969179       1  0.000928
26630990503       1  0.000928
27992420977       1  0.000928
28885867828       1  0.000928

[1077 rows x 2 columns]

In [26]:
df.corr()

,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
ranknow,1.000000,-0.554967,-0.553883,-0.557980,-0.555795,0.238924,-0.190846,0.009831,-0.365617
open,-0.554967,1.000000,0.998476,0.996331,0.996178,-0.172951,0.471700,0.032038,0.728775
high,-0.553883,0.998476,1.000000,0.995825,0.998219,-0.172393,0.473178,0.043980,0.744704
low,-0.557980,0.996331,0.995825,1.000000,0.997930,-0.174601,0.472075,0.042325,0.680669
close,-0.555795,0.996178,0.998219,0.997930,1.000000,-0.173448,0.473884,0.058502,0.715019
volume,0.238924,-0.172951,-0.172393,-0.174601,-0.173448,1.000000,0.514875,0.022462,-0.106978
market_price,-0.190846,0.471700,0.473178,0.472075,0.473884,0.514875,1.000000,0.033850,0.345995
close_ratio,0.009831,0.032038,0.043980,0.042325,0.058502,0.022462,0.033850,1.000000,0.043508
spread,-0.365617,0.728775,0.744704,0.680669,0.715019,-0.106978,0.345995,0.043508,1.000000

Before Pre-Processing:

In [27]:
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47

After Pre-Processing:

In [28]:
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [29]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)

In [30]:
df.head(20)

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,3,3,3,742,1,468,457,478,468,9,240,192,88
1,3,3,3,745,1,467,449,292,284,100,36,8,136
2,3,3,3,748,1,274,298,270,272,78,30,238,25
3,3,3,3,666,1,278,268,273,275,53,31,704,9
4,3,3,3,669,1,276,369,280,382,141,68,819,47
5,3,3,3,672,1,383,380,357,394,161,120,780,41
6,3,3,3,675,1,393,422,410,437,214,184,773,72
7,3,3,3,678,1,433,433,449,437,222,185,120,51
8,3,3,3,681,1,432,417,442,431,179,177,345,31
9,3,3,3,684,1,427,412,402,422,207,166,724,58
10,3,3,3,687,1,420,404,412,392,154,150,16,39
11,3,3,3,690,1,393,384,402,384,142,138,0,24
12,3,3,3,693,1,389,383,410,398,143,158,537,15
13,3,3,3,698,1,396,401,418,415,188,182,676,28
14,3,3,3,701,1,414,403,426,412,156,176,183,21
15,3,3,3,704,1,409,399,426,410,125,174,176,13
16,3,3,3,707,1,407,392,423,407,145,170,407,11
17,3,3,3,710,1,405,387,416,395,123,153,0,13
18,3,3,3,713,1,394,375,406,386,135,143,69,11
19,3,3,3,716,1,386,372,400,388,128,145,643,14